services:
  - type: web
    name: embedding-api
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app:app --host 0.0.0.0 --port $PORT --workers 1"
    envVars:
      - key: PORT
        value: 10000
      - key: TRANSFORMERS_CACHE
        value: /opt/render/project/.cache
